<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>017d588e-94fb-4db9-b65d-786ef69e4508</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Prompts\*.md" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
